### ISSUE TITLE
Lib (urllib3) fail from local poetry build

### ISSUE THREAD

**Issue by dosumis** [linkml/schema-automator#123]
Tried local Poetry install as I have been unable to get any install via pip to work (I got as far as an install with this bug  when I try to run #122).

Trying to run schemauto with Poetry install => 

```
 schema-automator % ~/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/bin/schemauto ../cell-annotation-schema/BICAN_schema.json 
Traceback (most recent call last):
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/bin/schemauto", line 3, in <module>
    from schema_automator.cli import main
  File "/Users/do12/Documents/GitHub/schema-automator/schema_automator/__init__.py", line 1, in <module>
    from schema_automator.annotators import *
  File "/Users/do12/Documents/GitHub/schema-automator/schema_automator/annotators/__init__.py", line 1, in <module>
    from schema_automator.annotators.schema_annotator import SchemaAnnotator
  File "/Users/do12/Documents/GitHub/schema-automator/schema_automator/annotators/schema_annotator.py", line 7, in <module>
    from linkml_runtime.linkml_model import SchemaDefinition, Element, PermissibleValue, ClassDefinition, SlotDefinition
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/linkml_runtime/__init__.py", line 3, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 11, in <module>
    from linkml_runtime.utils.namespaces import Namespaces
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/linkml_runtime/utils/namespaces.py", line 4, in <module>
    from prefixcommons import curie_util
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/prefixcommons/__init__.py", line 4, in <module>
    from .curie_util import expand_uri, contract_uri, NoPrefix
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/prefixcommons/curie_util.py", line 5, in <module>
    import requests
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/do12/Library/Caches/pypoetry/virtualenvs/schema-automator-coqgtRXk-py3.9/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by amc-corey-cox** [comment]
Closing — this was a user environment issue: LibreSSL 2.8.3 on old macOS is incompatible with urllib3 v2. Python 3.9 is no longer supported (#184), and modern macOS ships compatible SSL. Related to #122.
